# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mHB5yEUhn0JkyIgOJM-TCXbJWe70rt-4
"""

import pygame
import time

# Pygame-ni ishga tushirish
pygame.init()

# Oyna o'lchamlari
window_size = (200, 400)
screen = pygame.display.set_mode(window_size)
pygame.display.set_caption("Svitafor")

# Ranglar
black = (0, 0, 0)
white = (255, 255, 255)
red = (255, 0, 0)
yellow = (255, 255, 0)
green = (0, 255, 0)

# Doira joylashuvi
light_radius = 50
light_positions = [(100, 100), (100, 200), (100, 300)]

# Asosiy funksiya
def main():
    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        # Qizil chiroq
        screen.fill(black)
        draw_lights(active_light=0)
        pygame.display.update()
        time.sleep(2)

        # Sariq chiroq
        screen.fill(black)
        draw_lights(active_light=1)
        pygame.display.update()
        time.sleep(1)

        # Yashil chiroq
        screen.fill(black)
        draw_lights(active_light=2)
        pygame.display.update()
        time.sleep(2)

    pygame.quit()

# Chiroqlarni chizish funksiyasi
def draw_lights(active_light):
    colors = [red, yellow, green]
    for i in range(3):
        color = colors[i] if i == active_light else white
        pygame.draw.circle(screen, color, light_positions[i], light_radius)

# Dastur ishga tushiriladi
if name == "main":
    main()